// -------------------------------------------------------------
// 
// File Name: C:\Users\team06\Documents\MATLAB\Examples\R2022b\visionhdl\BlobAnalysisExample\verilog_hdl\BlobAnalysisHDL\bit2RGB.v
// Created: 2022-12-23 11:30:02
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: bit2RGB
// Source Path: BlobAnalysisHDL/BlobDetector/CCA_Algorithm/PaletteMap/bit2RGB
// Hierarchy Level: 3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module bit2RGB
          (In1,
           Out1_0,
           Out1_1,
           Out1_2);


  input   [23:0] In1;  // ufix24
  output  [7:0] Out1_0;  // uint8
  output  [7:0] Out1_1;  // uint8
  output  [7:0] Out1_2;  // uint8


  wire [7:0] Red_out1;  // uint8
  wire [7:0] Green_out1;  // uint8
  wire [7:0] Blue_out1;  // uint8


  assign Red_out1 = In1[23:16];



  assign Out1_0 = Red_out1;

  assign Green_out1 = In1[15:8];



  assign Out1_1 = Green_out1;

  assign Blue_out1 = In1[7:0];



  assign Out1_2 = Blue_out1;

endmodule  // bit2RGB

