// -------------------------------------------------------------
// 
// File Name: C:\Users\team06\Documents\MATLAB\Examples\R2022b\visionhdl\BlobAnalysisExample\verilog_hdl\BlobAnalysisHDL\npts_accum.v
// Created: 2022-12-23 11:30:02
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: npts_accum
// Source Path: BlobAnalysisHDL/BlobDetector/CCA_Algorithm/cca/npts_accum
// Hierarchy Level: 3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module npts_accum
          (clk,
           reset,
           enb,
           Inc,
           Rst,
           En,
           blobIdx,
           Cnt);


  input   clk;
  input   reset;
  input   enb;
  input   [16:0] Inc;  // ufix17
  input   Rst;
  input   En;
  input   [9:0] blobIdx;  // ufix10
  output  [16:0] Cnt;  // ufix17


  reg  xincr;
  reg  xincr_1;
  wire wren;
  wire NOT_out1;
  reg [9:0] wraddr;  // ufix10
  wire Relational_Operator_relop1;
  reg  sameIdx;
  wire Logical_Operator1_out1;
  reg [16:0] xincr_2;  // ufix17
  wire [16:0] zero_out1;  // ufix17
  wire [16:0] din;  // ufix17
  reg [16:0] incrVal;  // ufix17
  wire [16:0] rdout;  // ufix17
  wire [16:0] dataAccumVal;  // ufix17
  wire [17:0] Add_1;  // ufix18
  wire [17:0] Add_2;  // ufix18
  wire [17:0] din_1;  // ufix18
  wire [16:0] din_dtc;  // ufix17
  wire [16:0] din_2;  // ufix17
  wire [16:0] wrout;  // ufix17


  always @(posedge clk or posedge reset)
    begin : Delay5_process
      if (reset == 1'b1) begin
        xincr <= 1'b0;
      end
      else begin
        if (enb) begin
          xincr <= Rst;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : Delay6_process
      if (reset == 1'b1) begin
        xincr_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          xincr_1 <= En;
        end
      end
    end



  assign wren = xincr | xincr_1;



  assign NOT_out1 =  ~ wren;



  always @(posedge clk or posedge reset)
    begin : Delay1_process
      if (reset == 1'b1) begin
        wraddr <= 10'b0000000000;
      end
      else begin
        if (enb) begin
          wraddr <= blobIdx;
        end
      end
    end



  assign Relational_Operator_relop1 = wraddr == blobIdx;



  always @(posedge clk or posedge reset)
    begin : Delay4_process
      if (reset == 1'b1) begin
        sameIdx <= 1'b0;
      end
      else begin
        if (enb) begin
          sameIdx <= Relational_Operator_relop1;
        end
      end
    end



  assign Logical_Operator1_out1 = xincr | NOT_out1;



  always @(posedge clk or posedge reset)
    begin : Delay3_process
      if (reset == 1'b1) begin
        xincr_2 <= 17'b00000000000000000;
      end
      else begin
        if (enb) begin
          xincr_2 <= Inc;
        end
      end
    end



  assign zero_out1 = 17'b00000000000000000;



  always @(posedge clk or posedge reset)
    begin : Delay2_process
      if (reset == 1'b1) begin
        incrVal <= 17'b00000000000000000;
      end
      else begin
        if (enb) begin
          incrVal <= din;
        end
      end
    end



  assign dataAccumVal = (sameIdx == 1'b0 ? rdout :
              incrVal);



  assign Add_1 = {1'b0, dataAccumVal};
  assign Add_2 = {1'b0, xincr_2};
  assign din_1 = Add_1 + Add_2;



  assign din_dtc = din_1[16:0];



  assign din = (Logical_Operator1_out1 == 1'b0 ? din_dtc :
              zero_out1);



  assign din_2 = din;

  DualPortRAM_generic #(.AddrWidth(10),
                        .DataWidth(17)
                        )
                      u_Dual_Port_RAM_System (.clk(clk),
                                              .enb(enb),
                                              .wr_din(din_2),
                                              .wr_addr(wraddr),
                                              .wr_en(wren),
                                              .rd_addr(blobIdx),
                                              .wr_dout(wrout),
                                              .rd_dout(rdout)
                                              );

  assign Cnt = rdout;

endmodule  // npts_accum

