// -------------------------------------------------------------
// 
// File Name: C:\Users\team06\Documents\MATLAB\Examples\R2022b\visionhdl\BlobAnalysisExample\verilog_hdl\BlobAnalysisHDL\TimingSubsystem.v
// Created: 2022-12-23 11:30:02
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: TimingSubsystem
// Source Path: BlobAnalysisHDL/BlobDetector/CCA_Algorithm/TimingSubsystem
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module TimingSubsystem
          (clk,
           reset,
           enb,
           Vid_i,
           Ctrl_i_hStart,
           Ctrl_i_hEnd,
           Ctrl_i_vStart,
           Ctrl_i_vEnd,
           Ctrl_i_valid,
           Vid_o,
           Ctrl_o_hStart,
           Ctrl_o_hEnd,
           Ctrl_o_vStart,
           Ctrl_o_vEnd,
           Ctrl_o_valid,
           Rst_o,
           X,
           Y);


  input   clk;
  input   reset;
  input   enb;
  input   Vid_i;
  input   Ctrl_i_hStart;
  input   Ctrl_i_hEnd;
  input   Ctrl_i_vStart;
  input   Ctrl_i_vEnd;
  input   Ctrl_i_valid;
  output  Vid_o;
  output  Ctrl_o_hStart;
  output  Ctrl_o_hEnd;
  output  Ctrl_o_vStart;
  output  Ctrl_o_vEnd;
  output  Ctrl_o_valid;
  output  Rst_o;
  output  [8:0] X;  // ufix9
  output  [7:0] Y;  // uint8


  wire create_rst_out1;
  wire create_rst_out2_hStart;
  wire create_rst_out2_hEnd;
  wire create_rst_out2_vStart;
  wire create_rst_out2_vEnd;
  wire create_rst_out2_valid;
  wire create_rst_out3;
  wire [8:0] Pix_Pos_out1;  // ufix9
  wire [7:0] Pix_Pos_out2;  // uint8


  create_rst u_create_rst (.clk(clk),
                           .reset(reset),
                           .enb(enb),
                           .Video_i(Vid_i),
                           .ctrl_i_hStart(Ctrl_i_hStart),
                           .ctrl_i_hEnd(Ctrl_i_hEnd),
                           .ctrl_i_vStart(Ctrl_i_vStart),
                           .ctrl_i_vEnd(Ctrl_i_vEnd),
                           .ctrl_i_valid(Ctrl_i_valid),
                           .Video_o(create_rst_out1),
                           .Ctrl_o_hStart(create_rst_out2_hStart),
                           .Ctrl_o_hEnd(create_rst_out2_hEnd),
                           .Ctrl_o_vStart(create_rst_out2_vStart),
                           .Ctrl_o_vEnd(create_rst_out2_vEnd),
                           .Ctrl_o_valid(create_rst_out2_valid),
                           .Rst(create_rst_out3)
                           );

  assign Vid_o = create_rst_out1;

  assign Ctrl_o_hStart = create_rst_out2_hStart;

  assign Ctrl_o_hEnd = create_rst_out2_hEnd;

  assign Ctrl_o_vStart = create_rst_out2_vStart;

  assign Ctrl_o_vEnd = create_rst_out2_vEnd;

  assign Ctrl_o_valid = create_rst_out2_valid;

  assign Rst_o = create_rst_out3;

  Pix_Pos u_Pix_Pos (.clk(clk),
                     .reset(reset),
                     .enb(enb),
                     .Ctrl_i_hEnd(create_rst_out2_hEnd),
                     .Ctrl_i_valid(create_rst_out2_valid),
                     .Rst(create_rst_out3),
                     .Column(Pix_Pos_out1),  // ufix9
                     .Row(Pix_Pos_out2)  // uint8
                     );

  assign X = Pix_Pos_out1;

  assign Y = Pix_Pos_out2;

endmodule  // TimingSubsystem

