vlib work
vmap -c
vlog  bit2RGB.v
vlog  PaletteMap.v
vlog  SimpleDualPortRAM_generic.v
vlog  SimpleDualPortRAM_generic_block.v
vlog  Pixel_Stream_FIFO.v
vlog  Pix_Pos.v
vlog  create_rst.v
vlog  TimingSubsystem.v
vlog  Hold_Signal.v
vlog  Hold_Signal1.v
vlog  Hold_Signal_block.v
vlog  counterTrigger.v
vlog  SimpleDualPortRAM_generic_block1.v
vlog  HDL_FIFO.v
vlog  Merge.v
vlog  SingleEdgeDetectorL2H1.v
vlog  Subsystem.v
vlog  nfp_convert_single_to_fix_32_En30.v
vlog  nfp_convert_fix_17_En0_to_single.v
vlog  nfp_recip_single.v
vlog  accum_to_pos.v
vlog  labelandmerge.v
vlog  SimpleDualPortRAM_singlebit.v
vlog  ReadBlobs.v
vlog  DualPortRAM_generic.v
vlog  x_accum.v
vlog  y_accum.v
vlog  npts_accum.v
vlog  splitBBoxNEW.v
vlog  splitBBoxRAM.v
vlog  resolve.v
vlog  bbox_store.v
vlog  cca.v
vlog  includeBorder.v
vlog  gatheroutput.v
vlog  InputControlValidation.v
vlog  DataReadController.v
vlog  LineSpaceAverager.v
vlog  LineInfoStore.v
vlog  PushPopCounterOne.v
vlog  PushPopCounter.v
vlog  DATA_MEMORY.v
vlog  LineInfoStore_block.v
vlog  PaddingController.v
vlog  GateProcessData.v
vlog  Horizontal_Padder.v
vlog  Vertical_Padding_Counter.v
vlog  Vertical_Padder.v
vlog  LineBuffer.v
vlog  DilationCore.v
vlog  InputControlValidation_block.v
vlog  DataReadController_block.v
vlog  LineSpaceAverager_block.v
vlog  LineInfoStore_block1.v
vlog  PushPopCounterOne_block.v
vlog  PushPopCounter_block.v
vlog  DATA_MEMORY_block.v
vlog  LineInfoStore_block2.v
vlog  PaddingController_block.v
vlog  GateProcessData_block.v
vlog  Horizontal_Padder_block.v
vlog  Vertical_Padding_Counter_block.v
vlog  Vertical_Padder_block.v
vlog  LineBuffer_block.v
vlog  ErosionCore.v
vlog  Closing.v
vlog  Pixel_Stream_Aligner.v
vlog  CCA_Algorithm.v
vlog  splitBBox.v
vlog  SimpleDualPortRAM_generic_block2.v
vlog  CacheResultForXfer.v
vlog  FrameBoundary.v
vlog  Hold_Signal_block1.v
vlog  RGB2INTENSITY.v
vlog  Color_Space_Converter.v
vlog  Pixel_Stream_Aligner_block.v
vlog  BlobDetector.v
