// -------------------------------------------------------------
// 
// File Name: C:\Users\team06\Documents\MATLAB\Examples\R2022b\visionhdl\BlobAnalysisExample\verilog_hdl\BlobAnalysisHDL\Horizontal_Padder.v
// Created: 2022-12-23 11:30:02
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Horizontal_Padder
// Source Path: BlobAnalysisHDL/BlobDetector/CCA_Algorithm/Closing/LineBuffer/Horizontal Padder
// Hierarchy Level: 4
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Horizontal_Padder
          (clk,
           reset,
           enb,
           dataVectorIn_0,
           dataVectorIn_1,
           dataVectorIn_2,
           dataVectorIn_3,
           horPadCount,
           padShift,
           dataVector_0,
           dataVector_1,
           dataVector_2,
           dataVector_3);


  input   clk;
  input   reset;
  input   enb;
  input   dataVectorIn_0;  // boolean
  input   dataVectorIn_1;  // boolean
  input   dataVectorIn_2;  // boolean
  input   dataVectorIn_3;  // boolean
  input   [10:0] horPadCount;  // ufix11
  input   padShift;
  output  dataVector_0;  // boolean
  output  dataVector_1;  // boolean
  output  dataVector_2;  // boolean
  output  dataVector_3;  // boolean


  wire [0:3] DataPadValue;  // boolean [4]
  wire intdelay_out_1;
  reg  [0:1] intdelay_1_reg;  // ufix1 [2]
  wire intdelay_out_2;
  wire intdelay_out_3;
  wire intdelay_out_4;
  reg  [0:1] intdelay_1_reg_1;  // ufix1 [2]
  reg  [0:1] intdelay_1_reg_2;  // ufix1 [2]
  reg  [0:1] intdelay_1_reg_3;  // ufix1 [2]
  wire [0:1] intdelay_1_reg_next;  // ufix1 [2]
  wire [0:1] intdelay_1_reg_next_1;  // ufix1 [2]
  wire [0:1] intdelay_1_reg_next_2;  // ufix1 [2]
  wire [0:1] intdelay_1_reg_next_3;  // ufix1 [2]
  wire [0:3] DataMuxIn;  // boolean [4]
  wire [0:3] dataVector;  // boolean [4]


  assign DataPadValue[0] = 1'b0;
  assign DataPadValue[1] = 1'b0;
  assign DataPadValue[2] = 1'b0;
  assign DataPadValue[3] = 1'b0;



  always @(posedge clk or posedge reset)
    begin : intdelay_1_process
      if (reset == 1'b1) begin
        intdelay_1_reg[0] <= 1'b0;
        intdelay_1_reg[1] <= 1'b0;
        intdelay_1_reg_1[0] <= 1'b0;
        intdelay_1_reg_1[1] <= 1'b0;
        intdelay_1_reg_2[0] <= 1'b0;
        intdelay_1_reg_2[1] <= 1'b0;
        intdelay_1_reg_3[0] <= 1'b0;
        intdelay_1_reg_3[1] <= 1'b0;
      end
      else begin
        if (enb && padShift) begin
          intdelay_1_reg[0] <= intdelay_1_reg_next[0];
          intdelay_1_reg[1] <= intdelay_1_reg_next[1];
          intdelay_1_reg_1[0] <= intdelay_1_reg_next_1[0];
          intdelay_1_reg_1[1] <= intdelay_1_reg_next_1[1];
          intdelay_1_reg_2[0] <= intdelay_1_reg_next_2[0];
          intdelay_1_reg_2[1] <= intdelay_1_reg_next_2[1];
          intdelay_1_reg_3[0] <= intdelay_1_reg_next_3[0];
          intdelay_1_reg_3[1] <= intdelay_1_reg_next_3[1];
        end
      end
    end

  assign intdelay_1_reg_next[0] = dataVectorIn_0;
  assign intdelay_1_reg_next[1] = intdelay_1_reg[0];
  assign intdelay_out_1 = intdelay_1_reg[1];
  assign intdelay_1_reg_next_1[0] = dataVectorIn_1;
  assign intdelay_1_reg_next_1[1] = intdelay_1_reg_1[0];
  assign intdelay_out_2 = intdelay_1_reg_1[1];
  assign intdelay_1_reg_next_2[0] = dataVectorIn_2;
  assign intdelay_1_reg_next_2[1] = intdelay_1_reg_2[0];
  assign intdelay_out_3 = intdelay_1_reg_2[1];
  assign intdelay_1_reg_next_3[0] = dataVectorIn_3;
  assign intdelay_1_reg_next_3[1] = intdelay_1_reg_3[0];
  assign intdelay_out_4 = intdelay_1_reg_3[1];



  assign DataMuxIn[0] = intdelay_out_1;
  assign DataMuxIn[1] = intdelay_out_2;
  assign DataMuxIn[2] = intdelay_out_3;
  assign DataMuxIn[3] = intdelay_out_4;

  assign dataVector[0] = (horPadCount == 11'b00000000000 ? DataPadValue[0] :
              (horPadCount == 11'b00000000001 ? DataPadValue[0] :
              (horPadCount == 11'b00000000010 ? DataMuxIn[0] :
              DataPadValue[0])));
  assign dataVector[1] = (horPadCount == 11'b00000000000 ? DataPadValue[1] :
              (horPadCount == 11'b00000000001 ? DataPadValue[1] :
              (horPadCount == 11'b00000000010 ? DataMuxIn[1] :
              DataPadValue[1])));
  assign dataVector[2] = (horPadCount == 11'b00000000000 ? DataPadValue[2] :
              (horPadCount == 11'b00000000001 ? DataPadValue[2] :
              (horPadCount == 11'b00000000010 ? DataMuxIn[2] :
              DataPadValue[2])));
  assign dataVector[3] = (horPadCount == 11'b00000000000 ? DataPadValue[3] :
              (horPadCount == 11'b00000000001 ? DataPadValue[3] :
              (horPadCount == 11'b00000000010 ? DataMuxIn[3] :
              DataPadValue[3])));



  assign dataVector_0 = dataVector[0];

  assign dataVector_1 = dataVector[1];

  assign dataVector_2 = dataVector[2];

  assign dataVector_3 = dataVector[3];

endmodule  // Horizontal_Padder

