// -------------------------------------------------------------
// 
// File Name: C:\Users\team06\Documents\MATLAB\Examples\R2022b\visionhdl\BlobAnalysisExample\verilog_hdl\BlobAnalysisHDL\includeBorder.v
// Created: 2022-12-23 11:30:02
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: includeBorder
// Source Path: BlobAnalysisHDL/BlobDetector/CCA_Algorithm/gatheroutput/includeBorder
// Hierarchy Level: 3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module includeBorder
          (In1,
           Out1);


  input   [33:0] In1;  // ufix34
  output  [33:0] Out1;  // ufix34




  assign Out1 = In1;

endmodule  // includeBorder

