// -------------------------------------------------------------
// 
// File Name: C:\Users\team06\Documents\MATLAB\Examples\R2022b\visionhdl\BlobAnalysisExample\verilog_hdl\BlobAnalysisHDL\PaletteMap.v
// Created: 2022-12-23 11:30:02
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: PaletteMap
// Source Path: BlobAnalysisHDL/BlobDetector/CCA_Algorithm/PaletteMap
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module PaletteMap
          (clk,
           reset,
           enb,
           In1,
           Out1_0,
           Out1_1,
           Out1_2);


  input   clk;
  input   reset;
  input   enb;
  input   [9:0] In1;  // ufix10
  output  [7:0] Out1_0;  // uint8
  output  [7:0] Out1_1;  // uint8
  output  [7:0] Out1_2;  // uint8


  wire [19:0] Gain1_cast;  // ufix20_En11
  wire [7:0] Gain1_out1;  // uint8
  wire [7:0] Constant_out1;  // uint8
  wire [8:0] Add_1;  // ufix9
  wire [8:0] Add_2;  // ufix9
  wire [8:0] Add_out1;  // ufix9
  wire [9:0] Add_out1_dtc;  // ufix10
  wire [9:0] Switch_out1;  // ufix10
  wire [9:0] Saturation_out1;  // ufix10
  wire [7:0] alpha1_D_Lookup_Table_k;  // ufix8
  wire [23:0] alpha1_D_Lookup_Table_1 [0:255];  // ufix24 [256]
  wire [23:0] alpha1_D_Lookup_Table_out1;  // ufix24
  reg [23:0] Delay_out1;  // ufix24
  wire [7:0] bit2RGB_out1_0;  // uint8
  wire [7:0] bit2RGB_out1_1;  // uint8
  wire [7:0] bit2RGB_out1_2;  // uint8


  assign Gain1_cast = {1'b0, {In1, 9'b000000000}};
  assign Gain1_out1 = Gain1_cast[18:11];



  assign Constant_out1 = 8'b00000001;



  assign Add_1 = {1'b0, Gain1_out1};
  assign Add_2 = {1'b0, Constant_out1};
  assign Add_out1 = Add_1 + Add_2;



  assign Add_out1_dtc = {1'b0, Add_out1};



  assign Switch_out1 = (In1 == 10'b0000000000 ? In1 :
              Add_out1_dtc);



  assign Saturation_out1 = (Switch_out1 > 10'b0011111111 ? 10'b0011111111 :
              Switch_out1);



  assign alpha1_D_Lookup_Table_1[0] = 24'b000000000000000000000000;
  assign alpha1_D_Lookup_Table_1[1] = 24'b001100110110011000000000;
  assign alpha1_D_Lookup_Table_1[2] = 24'b001100111001101000000000;
  assign alpha1_D_Lookup_Table_1[3] = 24'b001100111100110100000000;
  assign alpha1_D_Lookup_Table_1[4] = 24'b001100111111111100000000;
  assign alpha1_D_Lookup_Table_1[5] = 24'b011001100011001100000000;
  assign alpha1_D_Lookup_Table_1[6] = 24'b011001100110011000000000;
  assign alpha1_D_Lookup_Table_1[7] = 24'b011001101001101000000000;
  assign alpha1_D_Lookup_Table_1[8] = 24'b011001101100110100000000;
  assign alpha1_D_Lookup_Table_1[9] = 24'b011001101111111100000000;
  assign alpha1_D_Lookup_Table_1[10] = 24'b100110100011001100000000;
  assign alpha1_D_Lookup_Table_1[11] = 24'b100110100110011000000000;
  assign alpha1_D_Lookup_Table_1[12] = 24'b100110101001101000000000;
  assign alpha1_D_Lookup_Table_1[13] = 24'b100110101100110100000000;
  assign alpha1_D_Lookup_Table_1[14] = 24'b100110101111111100000000;
  assign alpha1_D_Lookup_Table_1[15] = 24'b110011010011001100000000;
  assign alpha1_D_Lookup_Table_1[16] = 24'b110011010110011000000000;
  assign alpha1_D_Lookup_Table_1[17] = 24'b110011011001101000000000;
  assign alpha1_D_Lookup_Table_1[18] = 24'b110011011100110100000000;
  assign alpha1_D_Lookup_Table_1[19] = 24'b110011011111111100000000;
  assign alpha1_D_Lookup_Table_1[20] = 24'b111111110011001100000000;
  assign alpha1_D_Lookup_Table_1[21] = 24'b111111110110011000000000;
  assign alpha1_D_Lookup_Table_1[22] = 24'b111111111001101000000000;
  assign alpha1_D_Lookup_Table_1[23] = 24'b111111111100110100000000;
  assign alpha1_D_Lookup_Table_1[24] = 24'b111111111111111100000000;
  assign alpha1_D_Lookup_Table_1[25] = 24'b000000000011001100110011;
  assign alpha1_D_Lookup_Table_1[26] = 24'b000000000110011000110011;
  assign alpha1_D_Lookup_Table_1[27] = 24'b000000001001101000110011;
  assign alpha1_D_Lookup_Table_1[28] = 24'b000000001100110100110011;
  assign alpha1_D_Lookup_Table_1[29] = 24'b000000001111111100110011;
  assign alpha1_D_Lookup_Table_1[30] = 24'b001100110000000000110011;
  assign alpha1_D_Lookup_Table_1[31] = 24'b001100110110011000110011;
  assign alpha1_D_Lookup_Table_1[32] = 24'b001100111001101000110011;
  assign alpha1_D_Lookup_Table_1[33] = 24'b001100111100110100110011;
  assign alpha1_D_Lookup_Table_1[34] = 24'b001100111111111100110011;
  assign alpha1_D_Lookup_Table_1[35] = 24'b011001100000000000110011;
  assign alpha1_D_Lookup_Table_1[36] = 24'b011001100011001100110011;
  assign alpha1_D_Lookup_Table_1[37] = 24'b011001100110011000110011;
  assign alpha1_D_Lookup_Table_1[38] = 24'b011001101001101000110011;
  assign alpha1_D_Lookup_Table_1[39] = 24'b011001101100110100110011;
  assign alpha1_D_Lookup_Table_1[40] = 24'b011001101111111100110011;
  assign alpha1_D_Lookup_Table_1[41] = 24'b100110100000000000110011;
  assign alpha1_D_Lookup_Table_1[42] = 24'b100110100011001100110011;
  assign alpha1_D_Lookup_Table_1[43] = 24'b100110100110011000110011;
  assign alpha1_D_Lookup_Table_1[44] = 24'b100110101001101000110011;
  assign alpha1_D_Lookup_Table_1[45] = 24'b100110101100110100110011;
  assign alpha1_D_Lookup_Table_1[46] = 24'b100110101111111100110011;
  assign alpha1_D_Lookup_Table_1[47] = 24'b110011010000000000110011;
  assign alpha1_D_Lookup_Table_1[48] = 24'b110011010011001100110011;
  assign alpha1_D_Lookup_Table_1[49] = 24'b110011010110011000110011;
  assign alpha1_D_Lookup_Table_1[50] = 24'b110011011001101000110011;
  assign alpha1_D_Lookup_Table_1[51] = 24'b110011011100110100110011;
  assign alpha1_D_Lookup_Table_1[52] = 24'b110011011111111100110011;
  assign alpha1_D_Lookup_Table_1[53] = 24'b111111110000000000110011;
  assign alpha1_D_Lookup_Table_1[54] = 24'b111111110011001100110011;
  assign alpha1_D_Lookup_Table_1[55] = 24'b111111110110011000110011;
  assign alpha1_D_Lookup_Table_1[56] = 24'b111111111001101000110011;
  assign alpha1_D_Lookup_Table_1[57] = 24'b111111111100110100110011;
  assign alpha1_D_Lookup_Table_1[58] = 24'b111111111111111100110011;
  assign alpha1_D_Lookup_Table_1[59] = 24'b000000000011001101100110;
  assign alpha1_D_Lookup_Table_1[60] = 24'b000000000110011001100110;
  assign alpha1_D_Lookup_Table_1[61] = 24'b000000001001101001100110;
  assign alpha1_D_Lookup_Table_1[62] = 24'b000000001100110101100110;
  assign alpha1_D_Lookup_Table_1[63] = 24'b000000001111111101100110;
  assign alpha1_D_Lookup_Table_1[64] = 24'b001100110000000001100110;
  assign alpha1_D_Lookup_Table_1[65] = 24'b001100110011001101100110;
  assign alpha1_D_Lookup_Table_1[66] = 24'b001100110110011001100110;
  assign alpha1_D_Lookup_Table_1[67] = 24'b001100111001101001100110;
  assign alpha1_D_Lookup_Table_1[68] = 24'b001100111100110101100110;
  assign alpha1_D_Lookup_Table_1[69] = 24'b001100111111111101100110;
  assign alpha1_D_Lookup_Table_1[70] = 24'b011001100000000001100110;
  assign alpha1_D_Lookup_Table_1[71] = 24'b011001100011001101100110;
  assign alpha1_D_Lookup_Table_1[72] = 24'b011001101001101001100110;
  assign alpha1_D_Lookup_Table_1[73] = 24'b011001101100110101100110;
  assign alpha1_D_Lookup_Table_1[74] = 24'b011001101111111101100110;
  assign alpha1_D_Lookup_Table_1[75] = 24'b100110100000000001100110;
  assign alpha1_D_Lookup_Table_1[76] = 24'b100110100011001101100110;
  assign alpha1_D_Lookup_Table_1[77] = 24'b100110100110011001100110;
  assign alpha1_D_Lookup_Table_1[78] = 24'b100110101001101001100110;
  assign alpha1_D_Lookup_Table_1[79] = 24'b100110101100110101100110;
  assign alpha1_D_Lookup_Table_1[80] = 24'b100110101111111101100110;
  assign alpha1_D_Lookup_Table_1[81] = 24'b110011010000000001100110;
  assign alpha1_D_Lookup_Table_1[82] = 24'b110011010011001101100110;
  assign alpha1_D_Lookup_Table_1[83] = 24'b110011010110011001100110;
  assign alpha1_D_Lookup_Table_1[84] = 24'b110011011001101001100110;
  assign alpha1_D_Lookup_Table_1[85] = 24'b110011011100110101100110;
  assign alpha1_D_Lookup_Table_1[86] = 24'b110011011111111101100110;
  assign alpha1_D_Lookup_Table_1[87] = 24'b111111110000000001100110;
  assign alpha1_D_Lookup_Table_1[88] = 24'b111111110011001101100110;
  assign alpha1_D_Lookup_Table_1[89] = 24'b111111110110011001100110;
  assign alpha1_D_Lookup_Table_1[90] = 24'b111111111001101001100110;
  assign alpha1_D_Lookup_Table_1[91] = 24'b111111111100110101100110;
  assign alpha1_D_Lookup_Table_1[92] = 24'b111111111111111101100110;
  assign alpha1_D_Lookup_Table_1[93] = 24'b000000000011001110011010;
  assign alpha1_D_Lookup_Table_1[94] = 24'b000000000110011010011010;
  assign alpha1_D_Lookup_Table_1[95] = 24'b000000001001101010011010;
  assign alpha1_D_Lookup_Table_1[96] = 24'b000000001100110110011010;
  assign alpha1_D_Lookup_Table_1[97] = 24'b000000001111111110011010;
  assign alpha1_D_Lookup_Table_1[98] = 24'b001100110000000010011010;
  assign alpha1_D_Lookup_Table_1[99] = 24'b001100110011001110011010;
  assign alpha1_D_Lookup_Table_1[100] = 24'b001100110110011010011010;
  assign alpha1_D_Lookup_Table_1[101] = 24'b001100111001101010011010;
  assign alpha1_D_Lookup_Table_1[102] = 24'b001100111100110110011010;
  assign alpha1_D_Lookup_Table_1[103] = 24'b001100111111111110011010;
  assign alpha1_D_Lookup_Table_1[104] = 24'b011001100000000010011010;
  assign alpha1_D_Lookup_Table_1[105] = 24'b011001100011001110011010;
  assign alpha1_D_Lookup_Table_1[106] = 24'b011001100110011010011010;
  assign alpha1_D_Lookup_Table_1[107] = 24'b011001101001101010011010;
  assign alpha1_D_Lookup_Table_1[108] = 24'b011001101100110110011010;
  assign alpha1_D_Lookup_Table_1[109] = 24'b011001101111111110011010;
  assign alpha1_D_Lookup_Table_1[110] = 24'b100110100000000010011010;
  assign alpha1_D_Lookup_Table_1[111] = 24'b100110100011001110011010;
  assign alpha1_D_Lookup_Table_1[112] = 24'b100110100110011010011010;
  assign alpha1_D_Lookup_Table_1[113] = 24'b100110101100110110011010;
  assign alpha1_D_Lookup_Table_1[114] = 24'b100110101111111110011010;
  assign alpha1_D_Lookup_Table_1[115] = 24'b110011010000000010011010;
  assign alpha1_D_Lookup_Table_1[116] = 24'b110011010011001110011010;
  assign alpha1_D_Lookup_Table_1[117] = 24'b110011010110011010011010;
  assign alpha1_D_Lookup_Table_1[118] = 24'b110011011001101010011010;
  assign alpha1_D_Lookup_Table_1[119] = 24'b110011011100110110011010;
  assign alpha1_D_Lookup_Table_1[120] = 24'b110011011111111110011010;
  assign alpha1_D_Lookup_Table_1[121] = 24'b111111110000000010011010;
  assign alpha1_D_Lookup_Table_1[122] = 24'b111111110011001110011010;
  assign alpha1_D_Lookup_Table_1[123] = 24'b111111110110011010011010;
  assign alpha1_D_Lookup_Table_1[124] = 24'b111111111001101010011010;
  assign alpha1_D_Lookup_Table_1[125] = 24'b111111111100110110011010;
  assign alpha1_D_Lookup_Table_1[126] = 24'b111111111111111110011010;
  assign alpha1_D_Lookup_Table_1[127] = 24'b000000000011001111001101;
  assign alpha1_D_Lookup_Table_1[128] = 24'b000000000110011011001101;
  assign alpha1_D_Lookup_Table_1[129] = 24'b000000001001101011001101;
  assign alpha1_D_Lookup_Table_1[130] = 24'b000000001100110111001101;
  assign alpha1_D_Lookup_Table_1[131] = 24'b000000001111111111001101;
  assign alpha1_D_Lookup_Table_1[132] = 24'b001100110000000011001101;
  assign alpha1_D_Lookup_Table_1[133] = 24'b001100110011001111001101;
  assign alpha1_D_Lookup_Table_1[134] = 24'b001100110110011011001101;
  assign alpha1_D_Lookup_Table_1[135] = 24'b001100111001101011001101;
  assign alpha1_D_Lookup_Table_1[136] = 24'b001100111100110111001101;
  assign alpha1_D_Lookup_Table_1[137] = 24'b001100111111111111001101;
  assign alpha1_D_Lookup_Table_1[138] = 24'b011001100000000011001101;
  assign alpha1_D_Lookup_Table_1[139] = 24'b011001100011001111001101;
  assign alpha1_D_Lookup_Table_1[140] = 24'b011001100110011011001101;
  assign alpha1_D_Lookup_Table_1[141] = 24'b011001101001101011001101;
  assign alpha1_D_Lookup_Table_1[142] = 24'b011001101100110111001101;
  assign alpha1_D_Lookup_Table_1[143] = 24'b011001101111111111001101;
  assign alpha1_D_Lookup_Table_1[144] = 24'b100110100000000011001101;
  assign alpha1_D_Lookup_Table_1[145] = 24'b100110100011001111001101;
  assign alpha1_D_Lookup_Table_1[146] = 24'b100110100110011011001101;
  assign alpha1_D_Lookup_Table_1[147] = 24'b100110101001101011001101;
  assign alpha1_D_Lookup_Table_1[148] = 24'b100110101100110111001101;
  assign alpha1_D_Lookup_Table_1[149] = 24'b100110101111111111001101;
  assign alpha1_D_Lookup_Table_1[150] = 24'b110011010000000011001101;
  assign alpha1_D_Lookup_Table_1[151] = 24'b110011010011001111001101;
  assign alpha1_D_Lookup_Table_1[152] = 24'b110011010110011011001101;
  assign alpha1_D_Lookup_Table_1[153] = 24'b110011011001101011001101;
  assign alpha1_D_Lookup_Table_1[154] = 24'b110011011111111111001101;
  assign alpha1_D_Lookup_Table_1[155] = 24'b111111110000000011001101;
  assign alpha1_D_Lookup_Table_1[156] = 24'b111111110011001111001101;
  assign alpha1_D_Lookup_Table_1[157] = 24'b111111110110011011001101;
  assign alpha1_D_Lookup_Table_1[158] = 24'b111111111001101011001101;
  assign alpha1_D_Lookup_Table_1[159] = 24'b111111111100110111001101;
  assign alpha1_D_Lookup_Table_1[160] = 24'b111111111111111111001101;
  assign alpha1_D_Lookup_Table_1[161] = 24'b000000000011001111111111;
  assign alpha1_D_Lookup_Table_1[162] = 24'b000000000110011011111111;
  assign alpha1_D_Lookup_Table_1[163] = 24'b000000001001101011111111;
  assign alpha1_D_Lookup_Table_1[164] = 24'b000000001100110111111111;
  assign alpha1_D_Lookup_Table_1[165] = 24'b000000001111111111111111;
  assign alpha1_D_Lookup_Table_1[166] = 24'b001100110000000011111111;
  assign alpha1_D_Lookup_Table_1[167] = 24'b001100110011001111111111;
  assign alpha1_D_Lookup_Table_1[168] = 24'b001100110110011011111111;
  assign alpha1_D_Lookup_Table_1[169] = 24'b001100111001101011111111;
  assign alpha1_D_Lookup_Table_1[170] = 24'b001100111100110111111111;
  assign alpha1_D_Lookup_Table_1[171] = 24'b001100111111111111111111;
  assign alpha1_D_Lookup_Table_1[172] = 24'b011001100000000011111111;
  assign alpha1_D_Lookup_Table_1[173] = 24'b011001100011001111111111;
  assign alpha1_D_Lookup_Table_1[174] = 24'b011001100110011011111111;
  assign alpha1_D_Lookup_Table_1[175] = 24'b011001101001101011111111;
  assign alpha1_D_Lookup_Table_1[176] = 24'b011001101100110111111111;
  assign alpha1_D_Lookup_Table_1[177] = 24'b011001101111111111111111;
  assign alpha1_D_Lookup_Table_1[178] = 24'b100110100000000011111111;
  assign alpha1_D_Lookup_Table_1[179] = 24'b100110100011001111111111;
  assign alpha1_D_Lookup_Table_1[180] = 24'b100110100110011011111111;
  assign alpha1_D_Lookup_Table_1[181] = 24'b100110101001101011111111;
  assign alpha1_D_Lookup_Table_1[182] = 24'b100110101100110111111111;
  assign alpha1_D_Lookup_Table_1[183] = 24'b100110101111111111111111;
  assign alpha1_D_Lookup_Table_1[184] = 24'b110011010000000011111111;
  assign alpha1_D_Lookup_Table_1[185] = 24'b110011010011001111111111;
  assign alpha1_D_Lookup_Table_1[186] = 24'b110011010110011011111111;
  assign alpha1_D_Lookup_Table_1[187] = 24'b110011011001101011111111;
  assign alpha1_D_Lookup_Table_1[188] = 24'b110011011100110111111111;
  assign alpha1_D_Lookup_Table_1[189] = 24'b110011011111111111111111;
  assign alpha1_D_Lookup_Table_1[190] = 24'b111111110000000011111111;
  assign alpha1_D_Lookup_Table_1[191] = 24'b111111110011001111111111;
  assign alpha1_D_Lookup_Table_1[192] = 24'b111111110110011011111111;
  assign alpha1_D_Lookup_Table_1[193] = 24'b111111111001101011111111;
  assign alpha1_D_Lookup_Table_1[194] = 24'b111111111100110111111111;
  assign alpha1_D_Lookup_Table_1[195] = 24'b000100010000000000000000;
  assign alpha1_D_Lookup_Table_1[196] = 24'b001000100000000000000000;
  assign alpha1_D_Lookup_Table_1[197] = 24'b001100110000000000000000;
  assign alpha1_D_Lookup_Table_1[198] = 24'b010001000000000000000000;
  assign alpha1_D_Lookup_Table_1[199] = 24'b010101010000000000000000;
  assign alpha1_D_Lookup_Table_1[200] = 24'b011001100000000000000000;
  assign alpha1_D_Lookup_Table_1[201] = 24'b011101110000000000000000;
  assign alpha1_D_Lookup_Table_1[202] = 24'b100010010000000000000000;
  assign alpha1_D_Lookup_Table_1[203] = 24'b100110100000000000000000;
  assign alpha1_D_Lookup_Table_1[204] = 24'b101010110000000000000000;
  assign alpha1_D_Lookup_Table_1[205] = 24'b101111000000000000000000;
  assign alpha1_D_Lookup_Table_1[206] = 24'b110011010000000000000000;
  assign alpha1_D_Lookup_Table_1[207] = 24'b110111100000000000000000;
  assign alpha1_D_Lookup_Table_1[208] = 24'b111011110000000000000000;
  assign alpha1_D_Lookup_Table_1[209] = 24'b111111110000000000000000;
  assign alpha1_D_Lookup_Table_1[210] = 24'b000000000001000100000000;
  assign alpha1_D_Lookup_Table_1[211] = 24'b000000000010001000000000;
  assign alpha1_D_Lookup_Table_1[212] = 24'b000000000011001100000000;
  assign alpha1_D_Lookup_Table_1[213] = 24'b000000000100010000000000;
  assign alpha1_D_Lookup_Table_1[214] = 24'b000000000101010100000000;
  assign alpha1_D_Lookup_Table_1[215] = 24'b000000000110011000000000;
  assign alpha1_D_Lookup_Table_1[216] = 24'b000000000111011100000000;
  assign alpha1_D_Lookup_Table_1[217] = 24'b000000001000100100000000;
  assign alpha1_D_Lookup_Table_1[218] = 24'b000000001001101000000000;
  assign alpha1_D_Lookup_Table_1[219] = 24'b000000001010101100000000;
  assign alpha1_D_Lookup_Table_1[220] = 24'b000000001011110000000000;
  assign alpha1_D_Lookup_Table_1[221] = 24'b000000001100110100000000;
  assign alpha1_D_Lookup_Table_1[222] = 24'b000000001101111000000000;
  assign alpha1_D_Lookup_Table_1[223] = 24'b000000001110111100000000;
  assign alpha1_D_Lookup_Table_1[224] = 24'b000000001111111100000000;
  assign alpha1_D_Lookup_Table_1[225] = 24'b000000000000000000010001;
  assign alpha1_D_Lookup_Table_1[226] = 24'b000000000000000000100010;
  assign alpha1_D_Lookup_Table_1[227] = 24'b000000000000000000110011;
  assign alpha1_D_Lookup_Table_1[228] = 24'b000000000000000001000100;
  assign alpha1_D_Lookup_Table_1[229] = 24'b000000000000000001010101;
  assign alpha1_D_Lookup_Table_1[230] = 24'b000000000000000001100110;
  assign alpha1_D_Lookup_Table_1[231] = 24'b000000000000000001110111;
  assign alpha1_D_Lookup_Table_1[232] = 24'b000000000000000010001001;
  assign alpha1_D_Lookup_Table_1[233] = 24'b000000000000000010011010;
  assign alpha1_D_Lookup_Table_1[234] = 24'b000000000000000010101011;
  assign alpha1_D_Lookup_Table_1[235] = 24'b000000000000000010111100;
  assign alpha1_D_Lookup_Table_1[236] = 24'b000000000000000011001101;
  assign alpha1_D_Lookup_Table_1[237] = 24'b000000000000000011011110;
  assign alpha1_D_Lookup_Table_1[238] = 24'b000000000000000011101111;
  assign alpha1_D_Lookup_Table_1[239] = 24'b000000000000000011111111;
  assign alpha1_D_Lookup_Table_1[240] = 24'b000000000000000000000000;
  assign alpha1_D_Lookup_Table_1[241] = 24'b000100010001000100010001;
  assign alpha1_D_Lookup_Table_1[242] = 24'b001000100010001000100010;
  assign alpha1_D_Lookup_Table_1[243] = 24'b001100110011001100110011;
  assign alpha1_D_Lookup_Table_1[244] = 24'b010001000100010001000100;
  assign alpha1_D_Lookup_Table_1[245] = 24'b010101010101010101010101;
  assign alpha1_D_Lookup_Table_1[246] = 24'b011001100110011001100110;
  assign alpha1_D_Lookup_Table_1[247] = 24'b011101110111011101110111;
  assign alpha1_D_Lookup_Table_1[248] = 24'b100010011000100110001001;
  assign alpha1_D_Lookup_Table_1[249] = 24'b100110101001101010011010;
  assign alpha1_D_Lookup_Table_1[250] = 24'b101010111010101110101011;
  assign alpha1_D_Lookup_Table_1[251] = 24'b101111001011110010111100;
  assign alpha1_D_Lookup_Table_1[252] = 24'b110011011100110111001101;
  assign alpha1_D_Lookup_Table_1[253] = 24'b110111101101111011011110;
  assign alpha1_D_Lookup_Table_1[254] = 24'b111011111110111111101111;
  assign alpha1_D_Lookup_Table_1[255] = 24'b111111111111111111111111;
  assign alpha1_D_Lookup_Table_k = (Saturation_out1 == 10'b0000000000 ? 8'b00000000 :
              (Saturation_out1 >= 10'b0011111111 ? 8'b11111111 :
              Saturation_out1[7:0]));
  assign alpha1_D_Lookup_Table_out1 = alpha1_D_Lookup_Table_1[alpha1_D_Lookup_Table_k];



  always @(posedge clk or posedge reset)
    begin : Delay_process
      if (reset == 1'b1) begin
        Delay_out1 <= 24'b000000000000000000000000;
      end
      else begin
        if (enb) begin
          Delay_out1 <= alpha1_D_Lookup_Table_out1;
        end
      end
    end



  bit2RGB u_bit2RGB (.In1(Delay_out1),  // ufix24
                     .Out1_0(bit2RGB_out1_0),  // uint8
                     .Out1_1(bit2RGB_out1_1),  // uint8
                     .Out1_2(bit2RGB_out1_2)  // uint8
                     );

  assign Out1_0 = bit2RGB_out1_0;

  assign Out1_1 = bit2RGB_out1_1;

  assign Out1_2 = bit2RGB_out1_2;

endmodule  // PaletteMap

