// -------------------------------------------------------------
// 
// File Name: C:\Users\team06\Documents\MATLAB\Examples\R2022b\visionhdl\BlobAnalysisExample\verilog_hdl\BlobAnalysisHDL\resolve.v
// Created: 2022-12-23 11:30:02
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: resolve
// Source Path: BlobAnalysisHDL/BlobDetector/CCA_Algorithm/cca/bbox_store/resolve
// Hierarchy Level: 4
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module resolve
          (fromRAM,
           bbox,
           toRAM);


  input   [33:0] fromRAM;  // ufix34
  input   [33:0] bbox;  // ufix34
  output  [33:0] toRAM;  // ufix34


  wire [8:0] X1;  // ufix9
  wire [7:0] Y1;  // uint8
  wire [8:0] X2;  // ufix9
  wire [7:0] Y2;  // uint8
  wire [8:0] X1New;  // ufix9
  wire [7:0] Y1New;  // uint8
  wire [8:0] X2New;  // ufix9
  wire [7:0] Y2New;  // uint8
  wire Relational_Operator_relop1;
  wire [8:0] X1RAM;  // ufix9
  wire Relational_Operator1_relop1;
  wire [7:0] Y1RAM;  // uint8
  wire Relational_Operator2_relop1;
  wire [8:0] X2RAM;  // ufix9
  wire Relational_Operator3_relop1;
  wire Compare_To_Zero_out1;
  wire [7:0] Y2RAM;  // uint8
  wire [33:0] y;  // ufix34
  wire [33:0] Switch4_out1;  // ufix34


  splitBBoxRAM u_splitBBoxRAM (.In1(fromRAM),  // ufix34
                               .X1(X1),  // ufix9
                               .Y1(Y1),  // uint8
                               .X2(X2),  // ufix9
                               .Y2(Y2)  // uint8
                               );

  splitBBoxNEW u_splitBBoxNEW (.In1(bbox),  // ufix34
                               .X1(X1New),  // ufix9
                               .Y1(Y1New),  // uint8
                               .X2(X2New),  // ufix9
                               .Y2(Y2New)  // uint8
                               );

  assign Relational_Operator_relop1 = X1 < X1New;



  assign X1RAM = (Relational_Operator_relop1 == 1'b0 ? X1New :
              X1);



  assign Relational_Operator1_relop1 = Y1 < Y1New;



  assign Y1RAM = (Relational_Operator1_relop1 == 1'b0 ? Y1New :
              Y1);



  assign Relational_Operator2_relop1 = X2 > X2New;



  assign X2RAM = (Relational_Operator2_relop1 == 1'b0 ? X2New :
              X2);



  assign Relational_Operator3_relop1 = Y2 > Y2New;



  assign Compare_To_Zero_out1 = fromRAM == 34'h000000000;



  assign Y2RAM = (Relational_Operator3_relop1 == 1'b0 ? Y2New :
              Y2);



  assign y = {X1RAM, Y1RAM, X2RAM, Y2RAM};



  assign Switch4_out1 = (Compare_To_Zero_out1 == 1'b0 ? y :
              bbox);



  assign toRAM = Switch4_out1;

endmodule  // resolve

