// -------------------------------------------------------------
// 
// File Name: C:\Users\team06\Documents\MATLAB\Examples\R2022b\visionhdl\BlobAnalysisExample\verilog_hdl\BlobAnalysisHDL\SingleEdgeDetectorL2H1.v
// Created: 2022-12-23 11:30:02
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: SingleEdgeDetectorL2H1
// Source Path: BlobAnalysisHDL/BlobDetector/CCA_Algorithm/cca/SingleEdgeDetectorL2H1
// Hierarchy Level: 3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module SingleEdgeDetectorL2H1
          (clk,
           reset,
           enb,
           sync,
           Out1);


  input   clk;
  input   reset;
  input   enb;
  input   sync;
  output  Out1;


  reg  Unit_Delay_out1;
  wire Logical_Operator_out1;
  wire Logical_Operator2_out1;


  always @(posedge clk or posedge reset)
    begin : Unit_Delay_process
      if (reset == 1'b1) begin
        Unit_Delay_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Unit_Delay_out1 <= sync;
        end
      end
    end



  assign Logical_Operator_out1 = Unit_Delay_out1 ^ sync;



  assign Logical_Operator2_out1 = Logical_Operator_out1 & sync;



  assign Out1 = Logical_Operator2_out1;

endmodule  // SingleEdgeDetectorL2H1

