// -------------------------------------------------------------
// 
// File Name: C:\Users\team06\Documents\MATLAB\Examples\R2022b\visionhdl\BlobAnalysisExample\verilog_hdl\BlobAnalysisHDL\Vertical_Padder.v
// Created: 2022-12-23 11:30:02
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Vertical_Padder
// Source Path: BlobAnalysisHDL/BlobDetector/CCA_Algorithm/Closing/LineBuffer/Vertical Padder
// Hierarchy Level: 4
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Vertical_Padder
          (dataVectorIn_0,
           dataVectorIn_1,
           dataVectorIn_2,
           dataVectorIn_3,
           verPadCount,
           dataVectorOut_0,
           dataVectorOut_1,
           dataVectorOut_2,
           dataVectorOut_3);


  input   dataVectorIn_0;  // boolean
  input   dataVectorIn_1;  // boolean
  input   dataVectorIn_2;  // boolean
  input   dataVectorIn_3;  // boolean
  input   [10:0] verPadCount;  // ufix11
  output  dataVectorOut_0;  // boolean
  output  dataVectorOut_1;  // boolean
  output  dataVectorOut_2;  // boolean
  output  dataVectorOut_3;  // boolean


  wire verSEL1;
  wire DataPadValue;
  wire DataLineOut1;
  wire verSEL2;
  wire DataLineOut2;
  wire verSEL3;
  wire DataLineOut3;
  wire verSEL4;
  wire DataLineOut4;


  assign verSEL1 = verPadCount > 11'b00000000010;



  assign DataPadValue = 1'b0;



  assign DataLineOut1 = (verSEL1 == 1'b0 ? dataVectorIn_0 :
              DataPadValue);



  assign dataVectorOut_0 = DataLineOut1;

  assign verSEL2 = verPadCount > 11'b00000000011;



  assign DataLineOut2 = (verSEL2 == 1'b0 ? dataVectorIn_1 :
              DataPadValue);



  assign dataVectorOut_1 = DataLineOut2;

  assign verSEL3 = verPadCount < 11'b00000000001;



  assign DataLineOut3 = (verSEL3 == 1'b0 ? dataVectorIn_2 :
              DataPadValue);



  assign dataVectorOut_2 = DataLineOut3;

  assign verSEL4 = verPadCount < 11'b00000000010;



  assign DataLineOut4 = (verSEL4 == 1'b0 ? dataVectorIn_3 :
              DataPadValue);



  assign dataVectorOut_3 = DataLineOut4;

endmodule  // Vertical_Padder

