// -------------------------------------------------------------
// 
// File Name: C:\Users\team06\Documents\MATLAB\Examples\R2022b\visionhdl\BlobAnalysisExample\verilog_hdl\BlobAnalysisHDL\Vertical_Padding_Counter_block.v
// Created: 2022-12-23 11:30:02
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Vertical_Padding_Counter_block
// Source Path: BlobAnalysisHDL/BlobDetector/CCA_Algorithm/Closing/LineBuffer/Vertical Padding Counter
// Hierarchy Level: 4
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Vertical_Padding_Counter_block
          (clk,
           reset,
           enb,
           frameEnd,
           unloading,
           running,
           lineStart,
           VCount);


  input   clk;
  input   reset;
  input   enb;
  input   frameEnd;
  input   unloading;
  input   running;
  input   lineStart;
  output  [10:0] VCount;  // ufix11


  wire runningStart;
  wire unloadingStart;
  reg [10:0] VerticalPadCounter;  // ufix11
  wire prePad;
  wire runCountEn;
  wire verCountEn;


  assign runningStart = running & lineStart;



  assign unloadingStart = unloading & lineStart;



  assign prePad = VerticalPadCounter < 11'b00000000001;



  assign runCountEn = runningStart & prePad;



  assign verCountEn = runCountEn | unloadingStart;



  // Free running, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  always @(posedge clk or posedge reset)
    begin : Vertical_Counter_process
      if (reset == 1'b1) begin
        VerticalPadCounter <= 11'b00000000000;
      end
      else begin
        if (enb) begin
          if (frameEnd == 1'b1) begin
            VerticalPadCounter <= 11'b00000000000;
          end
          else if (verCountEn == 1'b1) begin
            VerticalPadCounter <= VerticalPadCounter + 11'b00000000001;
          end
        end
      end
    end



  assign VCount = VerticalPadCounter;

endmodule  // Vertical_Padding_Counter_block

